name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: |
          .next/
          public/
          package.json
          package-lock.json
          next.config.ts

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.ORACLE_CLOUD_SSH_KEY }}
        
    - name: Add Oracle Cloud server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.ORACLE_CLOUD_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to Oracle Cloud
      run: |
        # Create deployment package
        tar -czf deployment.tar.gz .next/ public/ package.json package-lock.json next.config.ts
        
        # Copy files to server
        scp deployment.tar.gz ${{ secrets.ORACLE_CLOUD_USER }}@${{ secrets.ORACLE_CLOUD_HOST }}:/tmp/
        scp scripts/deploy.sh ${{ secrets.ORACLE_CLOUD_USER }}@${{ secrets.ORACLE_CLOUD_HOST }}:/tmp/
        
        # Execute deployment script on server
        ssh ${{ secrets.ORACLE_CLOUD_USER }}@${{ secrets.ORACLE_CLOUD_HOST }} "chmod +x /tmp/deploy.sh && /tmp/deploy.sh"
        
    - name: Health Check
      run: |
        sleep 30
        curl -f http://${{ secrets.ORACLE_CLOUD_HOST }}:3000 || exit 1